TRUNCATE TABLE tbl_AdaptiveIndexDefrag_Analysis_log
TRUNCATE TABLE tbl_AdaptiveIndexDefrag_Exceptions
TRUNCATE TABLE tbl_AdaptiveIndexDefrag_IxDisableStatus
TRUNCATE TABLE tbl_AdaptiveIndexDefrag_log
TRUNCATE TABLE tbl_AdaptiveIndexDefrag_Stats_log
TRUNCATE TABLE tbl_AdaptiveIndexDefrag_Stats_Working
TRUNCATE TABLE tbl_AdaptiveIndexDefrag_Working